/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author andre
 */
public class Tanque extends javax.swing.JFrame {
    /**
     * Creates new form Tanque
     */
    int max = 0;
    Timer timer;
    boolean Detener = false;
    boolean ejecutando = false;
    public Tanque() {
        initComponents();
        ImageIcon tanque = new ImageIcon("img/TC8.png");
        int alto = Tanque.getHeight();
        int ancho = Tanque.getWidth();
        Image tanque_escalado = tanque.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH);
        ImageIcon tanque_final = new ImageIcon(tanque_escalado);
        Tanque.setIcon(tanque_final);
    }
    public void Cambiar_Imagen(double tanque_nivel, boolean abierto) {

        int canIdeal = Integer.parseInt(CantidadIdeal.getText());
        int canMax = Integer.parseInt(CantidadMax.getText());

        double porcentajeIdeal = (canIdeal * 100.0) / canMax;
        double mitadIdeal = porcentajeIdeal / 2;

        ImageIcon tanque;

        if (abierto) {
            //tanque vacio
            if (tanque_nivel < mitadIdeal) {
                tanque = new ImageIcon("img/TC7.png");
            }//tanque 25% lleno 
            else if (tanque_nivel < porcentajeIdeal) {
                tanque = new ImageIcon("img/TC6.png");
            }//tanque cerca del punto ideal 
            else if (tanque_nivel <= porcentajeIdeal + 2) {
                tanque = new ImageIcon("img/TC3.png");
            } //sobre pasado 
            else {
                tanque = new ImageIcon("img/TC2.png");
            }
        }//llave del tanque cerrado 
        else {
            if (tanque_nivel < mitadIdeal) {
                tanque = new ImageIcon("img/TC8.png");
            } else if (tanque_nivel < porcentajeIdeal) {
                tanque = new ImageIcon("img/TC5.png");
            } else if (tanque_nivel <= porcentajeIdeal + 2) {
                tanque = new ImageIcon("img/TC4.png");
            } else {
                tanque = new ImageIcon("img/TC1.png");
            }
        }
        //ajuste de imagen 
        int alto = Tanque.getHeight();
        int ancho = Tanque.getWidth();
        Image tanque_escalado = tanque.getImage().getScaledInstance(ancho,alto,Image.SCALE_SMOOTH);
        Tanque.setIcon(new ImageIcon(tanque_escalado));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fondo = new javax.swing.JPanel();
        Imagen = new javax.swing.JPanel();
        Tanque = new javax.swing.JLabel();
        Grafica = new javax.swing.JPanel();
        INICIAR = new javax.swing.JButton();
        abrir_cerrar = new javax.swing.JRadioButton();
        detener = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cantidadP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cantidadL = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CantidadMax = new javax.swing.JTextField();
        CantidadIdeal = new javax.swing.JTextField();
        mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 102));

        Imagen.setBackground(new java.awt.Color(102, 255, 255));

        javax.swing.GroupLayout ImagenLayout = new javax.swing.GroupLayout(Imagen);
        Imagen.setLayout(ImagenLayout);
        ImagenLayout.setHorizontalGroup(
            ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tanque, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        ImagenLayout.setVerticalGroup(
            ImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Tanque, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );

        Grafica.setBackground(new java.awt.Color(255, 102, 102));

        javax.swing.GroupLayout GraficaLayout = new javax.swing.GroupLayout(Grafica);
        Grafica.setLayout(GraficaLayout);
        GraficaLayout.setHorizontalGroup(
            GraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
        );
        GraficaLayout.setVerticalGroup(
            GraficaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        INICIAR.setText("INICIAR SIMULACION");
        INICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INICIARActionPerformed(evt);
            }
        });

        abrir_cerrar.setText("ABRIR/CERRAR");

        detener.setText("DETENER SIMULACION");
        detener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detenerActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 255, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(51, 255, 51));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Cantidad actual (%)");

        cantidadP.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cantidadP.setText("00");

        jLabel4.setBackground(new java.awt.Color(51, 255, 51));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Cantidad actual (L)");

        cantidadL.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        cantidadL.setText("00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(cantidadP)))
                .addGap(65, 65, 65))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(cantidadL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantidadL)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Cantidad ideal");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Cantidad maxima");

        CantidadMax.setColumns(3);
        CantidadMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CantidadMaxActionPerformed(evt);
            }
        });

        CantidadIdeal.setColumns(3);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(CantidadMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(CantidadIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantidadMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CantidadIdeal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        mensaje.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout FondoLayout = new javax.swing.GroupLayout(Fondo);
        Fondo.setLayout(FondoLayout);
        FondoLayout.setHorizontalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(detener)
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addComponent(INICIAR)
                        .addGap(192, 192, 192)
                        .addComponent(abrir_cerrar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, FondoLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(Grafica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        FondoLayout.setVerticalGroup(
            FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoLayout.createSequentialGroup()
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Grafica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(FondoLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(FondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INICIAR)
                    .addComponent(abrir_cerrar))
                .addGap(18, 18, 18)
                .addComponent(detener)
                .addGap(108, 108, 108))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INICIARActionPerformed
        //valida que los campos no esten vacios
        if (CantidadIdeal.getText().isEmpty() || CantidadMax.getText().isEmpty()) {
        mensaje.setText("Campos vacios!!");
        return;
    }
    int canM = Integer.parseInt(CantidadMax.getText());
    int canIdeal = Integer.parseInt(CantidadIdeal.getText());
    
    //valida que la cantidad ideal no sea mayor a el maximo
    if (canM < canIdeal+2) {
        mensaje.setText("La cantidad maxima es menor a la cantidad ideal");
        return;
    }
    //se limpia el label de mensaje cada que de la a iniciar
    mensaje.setText("");
    Detener = false;
    
    if (!ejecutando) {
        //se calcula el promedio que equivale la cantidad ideal con respecto a la cantidad maxima
        double canPro = (canIdeal * 100.0) / canM;
        ejecutando = true;
        
        //timer sirve para poder hacer la comparacion en intervalos de tiempo para que se vea mas fluido en la simulacion donde se da el tiempo en milisegundos
        timer = new Timer(70, e -> {
            //envio de los datos en porcentaje y en litro de la cantidad actual
            cantidadP.setText(max + "%");
            cantidadL.setText(((max * canM) / 100) + "L");
            
            Cambiar_Imagen(max, abrir_cerrar.isSelected());
            
            if (abrir_cerrar.isSelected()) {
                /*si la llave esta abierta y el valor absoluto es menor a 1 se redondea para una mayor presicion 
                porque la suma y resta de datos para el cambio de valores no son decimales por caso de que canpro es el
                promedio al tanque y puede llegar a tener decimales como 23.5% y al momento de restar cuando max es 23 
                dara 0.5 lo cual redondea a 24
                */
                if (Math.abs(max - canPro) < 1) {
                    max = (int) Math.round(canPro);
                } else if (max < canPro) {
                    max++;
                } else if (max > canPro) {
                    max--;
                }
            } else {
                //si esta cerrado solo suma constantemente
                if (max < 100) {
                    max++;
                }
            }
            //si detener es accionado max vuelve a 0 para otra simulacion y el tiempo se detiene para volver a iniciarse otra vez
            if (Detener) {
                max=0;
                timer.stop();
            }
        });
        //aqui se inicia todo lo que esta dentro de *time*
        timer.start();
    }
        
    }//GEN-LAST:event_INICIARActionPerformed

    private void detenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detenerActionPerformed
        Detener=true;
        ejecutando=false;
    }//GEN-LAST:event_detenerActionPerformed

    private void CantidadMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CantidadMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CantidadMaxActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tanque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tanque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CantidadIdeal;
    private javax.swing.JTextField CantidadMax;
    private javax.swing.JPanel Fondo;
    private javax.swing.JPanel Grafica;
    private javax.swing.JButton INICIAR;
    private javax.swing.JPanel Imagen;
    private javax.swing.JLabel Tanque;
    private javax.swing.JRadioButton abrir_cerrar;
    private javax.swing.JLabel cantidadL;
    private javax.swing.JLabel cantidadP;
    private javax.swing.JButton detener;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables
}
